
import React from 'react';
import { Track } from '../types';

interface HomeProps {
  recentTracks: Track[];
  onPlay: (track: Track) => void;
}

const Home: React.FC<HomeProps> = ({ recentTracks, onPlay }) => {
  const getTimeOfDay = () => {
    const hour = new Date().getHours();
    if (hour < 12) return 'Good morning';
    if (hour < 18) return 'Good afternoon';
    return 'Good evening';
  };

  return (
    <div className="space-y-10 animate-in fade-in duration-700">
      <section>
        <h2 className="text-3xl font-black mb-6 tracking-tighter">{getTimeOfDay()}</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {recentTracks.slice(0, 6).map((track) => (
            <div 
              key={track.id}
              onClick={() => onPlay(track)}
              className="flex items-center bg-white/5 hover:bg-white/10 rounded overflow-hidden group cursor-pointer transition-all duration-300"
            >
              <img src={track.album.images[0]?.url} className="w-20 h-20 shadow-2xl" alt={track.name} />
              <div className="flex-1 px-4 truncate">
                <p className="font-bold text-base truncate">{track.name}</p>
                <p className="text-xs text-gray-400">{track.artists[0].name}</p>
              </div>
              <button className="mr-4 w-12 h-12 bg-[#1DB954] rounded-full shadow-xl flex items-center justify-center opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-300 hover:scale-105 active:scale-95">
                <svg className="w-6 h-6 text-black fill-current" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
              </button>
            </div>
          ))}
        </div>
      </section>

      <section>
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-2xl font-bold hover:underline cursor-pointer tracking-tight">AI-Curated for You</h3>
          <button className="text-sm font-bold text-gray-400 hover:underline">Show all</button>
        </div>
        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6 gap-6">
          {[1, 2, 3, 4, 5, 6].map((i) => (
            <div key={i} className="bg-[#181818] hover:bg-[#282828] p-4 rounded-lg transition-all duration-300 cursor-pointer group shadow-lg border border-white/5">
              <div className="relative mb-4">
                <img 
                  src={`https://picsum.photos/seed/${i + 100}/300/300`} 
                  className="w-full aspect-square object-cover rounded shadow-2xl" 
                  alt="Playlist cover"
                />
                <button className="absolute bottom-2 right-2 w-12 h-12 bg-[#1DB954] rounded-full shadow-2xl flex items-center justify-center opacity-0 group-hover:opacity-100 translate-y-2 group-hover:translate-y-0 transition-all duration-300 hover:scale-105 shadow-black">
                  <svg className="w-6 h-6 text-black fill-current" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg>
                </button>
              </div>
              <h4 className="font-bold text-base mb-1 truncate">Gemini Discover {i}</h4>
              <p className="text-xs text-gray-400 line-clamp-2 leading-relaxed">Personalized mix generated by AI based on your recent activity.</p>
            </div>
          ))}
        </div>
      </section>

      {/* Featured AI Card */}
      <section className="bg-gradient-to-r from-blue-900/40 to-indigo-900/40 rounded-xl p-8 flex flex-col md:flex-row items-center justify-between border border-white/10 relative overflow-hidden group">
        <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
           <svg className="w-48 h-48 text-white" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2L4.5 20.29l.71.71L12 18l6.79 3 .71-.71z"/></svg>
        </div>
        <div className="z-10 text-center md:text-left mb-6 md:mb-0">
          <span className="text-xs font-bold uppercase tracking-widest text-blue-400 mb-2 block">Premium Feature</span>
          <h2 className="text-4xl font-black mb-4 tracking-tighter">Meet Gemini Music AI</h2>
          <p className="text-gray-300 max-w-lg mb-6 leading-relaxed">Explain your mood, your day, or a specific vibe, and let our AI build the perfect soundtrack for you in seconds.</p>
          <button className="bg-white text-black font-bold px-8 py-3 rounded-full hover:scale-105 transition active:scale-95 shadow-lg">
            Try AI Discovery
          </button>
        </div>
        <div className="relative z-10">
          <div className="w-48 h-48 bg-[#1DB954] rounded-full blur-3xl opacity-20 absolute -inset-4 animate-pulse"></div>
          <img src="https://picsum.photos/seed/ai-hero/400/400" className="w-56 h-56 rounded-2xl shadow-2xl rotate-3 group-hover:rotate-0 transition-transform duration-500" alt="AI Hero" />
        </div>
      </section>
    </div>
  );
};

export default Home;
